# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # General linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  # Golang lint and test
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: master
    hooks:
      - id: golangci-lint
        name: Run golangci-lint
        types: [go]
        pass_filenames: false
      - id: go-unit-tests
        name: Run go test
        types: [go]
        pass_filenames: false
